version: '3'
services:
  app:
    build: .
    image: code-generator:latest
    container_name: code-generator
    ports:
      - 8081:8081
    volumes:
      - .:/code-generator
    environment:
      - APP_PORT=8081