version: '3'
services:
  app:
    build: .
    image: code-generator:dev
    container_name: code-generator
    ports:
      - 8080:8080
    volumes:
      - .:/code-generator
    environment:
      - APP_PORT=8080
    command: tail -f /dev/null